route:
  # group_by: ['alertname']
  group_wait: 20s
  group_interval: 25s
  # repeat_interval: 30s
  receiver: discord_webhook

receivers:
    - name: 'discord_webhook'
      webhook_configs:
          - url: 'http://discord_webhook:9094'
